### ISSUE TITLE
corrected the 404 error for /care-routine

### ISSUE THREAD

**Issue by ishicodz** [Haimantika/zen-garden#2]
kindly review and merge my PR for the error.
Thank you :)
@Haimantika #1

**Comment by Haimantika** [comment]
Hi @ishicodz thanks for the PR, but it didn't work. I had to revert.

**Comment by ishicodz** [comment]
i have deployed the repo of my code on vercel, kindly check it out at [https://zen-garden-sage.vercel.app/](https://zen-garden-sage.vercel.app/)

basically the only thing you need to configure is in your vercel.json file mainly is dest under routes like this - `"dest": "src/backend/app.js"`
